name: Build Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup node 
      uses: actions/setup-node@v2
      with: 
        node-version:  '14.x'
    
    - name: NPM Install
      working-directory: ./NodejsWebApp
      run: npm install
      
    - name: Run Lint Code
      working-directory: ./NodejsWebApp
      run: npm run lint
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      if: success()
      
    - name: Push Docker Image
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - run: docker push ivish/node-web-app
      if: success() 
      
    - name: Pull and Run
      run: |
        docker run --memory=10m --cpus=1 -p 49160:80 ivish/node-web-app
        sleep 5 
        curl -i localhost:49160 
